import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>App Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto py-12">
        <h1 className="font-bold text-2xl">App Starter</h1>
      </main>

      <footer className="bg-gray-900 text-white">
        <div className="container mx-auto h-16 flex items-center justify-center">
          <p>App Starter &copy; {new Date().getFullYear()}</p>
        </div>
      </footer>
    </>
  );
};

export default Home;
