import type { NextPage, GetServerSidePropsContext } from "next";
import { useSession, getSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data, status } = useSession();
  return (
    <>
      <Head>
        <title>App Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto py-12">
        <h1 className="font-bold text-2xl">App Starter</h1>
        {data && <p>{data.user?.email}</p>}
      </section>
    </>
  );
};

export default Home;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      session: await getSession(context),
    },
  };
}
