import type { NextPage, GetServerSidePropsContext } from "next";
import { useSession, getSession } from "next-auth/react";
import Head from "next/head";

const Test: NextPage = () => {
  return (
    <>
      <Head>
        <title>Test | App Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto py-12">
        <h1 className="font-bold text-2xl">Test Page</h1>
      </section>
    </>
  );
};

export default Test;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getSession(context);
  if (session) {
    return {
      props: {
        session,
      },
    };
  }
  return {
    redirect: {
      destination: "/",
      permanent: false,
    },
  };
}
